In [25]:
import pandas as pd
import numpy as np
import sympy as sp
n = 7 # номер варианта
# генерирование СЛАУ для проверки - A1
A = np.matrix(np.ones((3,3)))
for i in range(3):
        for j in range(3):
            if j==i:
                A[i,j] = i + j + n +2
b1 = np.transpose(np.matrix([n + (i+2)*2 for i in range(3)]))
# генерирование плохо обусловленных СЛАУ - A21, А22

A_1 = np.eye(5)
A_2 = np.matrix(np.ones((5,5)))
for i in range(5):
        for j in range(5):
            if j > i:
                A_1[i,j] = -1
                A_2[i,j] = -1
# задание eps из условия
eps1 = 10**(-4)
eps2 = 10**(-6)                
B1 = A_1 + n*eps1*A_2 
B2 = A_1 + n*eps2*A_2 
b12 = np.transpose(np.matrix(np.ones(5)))
b12[4,0] = -1

A_1 = np.eye(6)
A_2 = np.matrix(np.ones((6,6)))
for i in range(6):
        for j in range(6):
            if j > i:
                A_1[i,j] = -1
                A_2[i,j] = -1              
B3 = A_1 + n*eps1*A_2 
B4 = A_1 + n*eps2*A_2 
b34 = np.transpose(np.matrix(np.ones(6)))
b34[5,0] = -1

A_1 = np.eye(7)
A_2 = np.matrix(np.ones((7,7)))
for i in range(7):
        for j in range(7):
            if j > i:
                A_1[i,j] = -1
                A_2[i,j] = -1              
B5 = A_1 + n*eps1*A_2 
B6 = A_1 + n*eps2*A_2 
b56 = np.transpose(np.matrix(np.ones(7)))
b56[6,0] = -1
All_mat = {0:A,1:B1,2:B2,3:B3,4:B4,5:B5,6:B6}
name_mat = {0:"A",1:"B1",2:"B2",3:"B3",4:"B4",5:"B5",6:"B6"}
name_vect = {0:b1,1:b12,2:b12,3:b34,4:b34,5:b56,6:b56}

In [26]:
print(A)
print(b1)

[[ 9.  1.  1.]
 [ 1. 11.  1.]
 [ 1.  1. 13.]]
[[11]
 [13]
 [15]]


In [27]:
print(B1)
print(B2)
print(b12)

[[ 1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00]]
[[ 1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00]
 [ 7.000000e-06  1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  1.000007e+00 -1.000007e+00 -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  7.000000e-06  1.000007e+00 -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  7.000000e-06  7.000000e-06  1.000007e+00]]
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]]


In [28]:
print(B3)
print(B4)
print(b34)

[[ 1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00]]
[[ 1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00
  -1.000007e+00]
 [ 7.000000e-06  1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00
  -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  1.000007e+00 -1.000007e+00 -1.000007e+00
  -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  7.000000e-06  1.000007e+00 -1.000007e+00
  -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  7.000000e-06  7.000000e-06  1.000007e+00
  -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  7.000000e-06  7.000000e-06  7.000000e-06
   1.000007e+00]]
[[ 1.]
 [ 1.]


In [29]:
print(B5)
print(B6)
print(b56)

[[ 1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00
  -1.0007e+00]
 [ 7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00
  -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00 -1.0007e+00
  -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00 -1.0007e+00
  -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00 -1.0007e+00
  -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  1.0007e+00
  -1.0007e+00]
 [ 7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04  7.0000e-04
   1.0007e+00]]
[[ 1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00
  -1.000007e+00 -1.000007e+00]
 [ 7.000000e-06  1.000007e+00 -1.000007e+00 -1.000007e+00 -1.000007e+00
  -1.000007e+00 -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  1.000007e+00 -1.000007e+00 -1.000007e+00
  -1.000007e+00 -1.000007e+00]
 [ 7.000000e-06  7.000000e-06  7.000000e-06  1.000007e+00 -1.000007

In [30]:
# 1 норма матрицы
def norma1(A):
    n = A.shape[0]
    s = 0
    s1 = 0
    for i in range(n):
        if s > s1:
            s1 = s
        s = 0
        for j in range(n):
            s += abs(A[i,j])
    if s > s1:
            s1 = s
    return s1

In [31]:
# 2 норма матрицы
def norma2(A):
    n = A.shape[0]
    s = 0
    s1 = 0
    for i in range(n):
        if s > s1:
            s1 = s
        s = 0
        for j in range(n):
            s += abs(A[j,i])
    if s > s1:
            s1 = s
    return s1

In [32]:
# 3 норма матрицы
def norma3(A):
    n = A.shape[0]
    s = 0
    for i in range(n):
        for j in range(n):
            s += (A[i,j])**2
    return s**(1/2)

In [33]:
# число обусловленности с помощю трёх разных норм
def v(A,k):
    n = A.shape[0]
    if k == 1:
        return norma1(A)*norma1(Gauss(A,np.eye(n)))
    if k == 2:
        return norma2(A)*norma2(Gauss(A,np.eye(n)))
    if k == 3:
        return norma3(A)*norma3(Gauss(A,np.eye(n)))

In [34]:
def v_table(dict1,dict2,dict3):
    table = pd.DataFrame({"Матрица":[],"v по норме 1":[],"v по норме 2":[],"v по норме 3":[],"количество итераций":[]})
    for i in range(7):
        a = All_mat[i]
        b = name_vect[i]
        line ={"Матрица":name_mat[i],"v по норме 1":v(a,1),"v по норме 2":v(a,2),"v по норме 3":v(a,3),"количество итераций":steep(a,b)}
        table = table.append(line,ignore_index=True)
    return table

In [35]:
v_table(All_mat,name_mat,name_vect)

Матрица  v по норме 1  v по норме 2  v по норме 3  количество итераций
0       A      1.958599      1.958599      3.236803                 38.0
1      B1     78.571612     78.571612     41.141629                 58.0
2      B2     79.985443     79.985443     41.885065                 52.0
3      B3    184.641741    184.641741     94.396554                175.0
4      B4    191.923423    191.923423     98.139048                 64.0
5      B5    413.325000    413.325000    208.493772               1138.0
6      B6    447.624001    447.624001    225.862676                101.0

In [18]:
# проверяем, есть ли на главной диагонали нули
def no0(M, k):
    n =  M.shape[0]
    while k < n and not M[k, k]:
        k += 1
    return k

In [ ]:
def Gauss(A,b):
        M = np.hstack((A, b)) # "склейка" матрицы коэффициентов при переменных и вектора свободных членов
        n = M.shape[0] 
        for k in range(n): 
            # убираем нули с главной диагонали, если они есть
            k0 = no0(M, k)
            if k0 != k:
                M[k0], M[k] = M[k].copy(), M[k0]   
            if M[k, k] != 1:
                M[k, :] *= 1 / M[k, k]
            # приямой ход метода Гаусса
            for r in range(k + 1, n):
                M[r, :] -= M[k, :] * M[r, k]
        #обратный ход метода Гаусса
        for k in range(n - 1, 0, -1):
            for r in range(k - 1, -1, -1):
                if M[r, k]:
                    M[r, :] -= M[k, :] * M[r, k]
        if b.shape[1] > 1:
            return np.hsplit(M,2)[1]
        return  (M[:,n])

In [20]:
# норма вектора
def norma(b):
    n = b.shape[0]
    if n == 1:
        b = np.transpose(b)
        n = b.shape[0]
    s = 0
    for j in range(n):
            s += (b[j])**2
    return np.sqrt(s)

In [1]:
# метод отражений
def mir(A, b):
    n = A.shape[0]
    for i in range(n-1):
        #генерирование вектора единичной длины - w
        z = np.eye(n)[i,i:n]
        y = np.transpose(A[i:n,i])
        a = np.linalg.norm(y)/np.linalg.norm(z) 
        w = (y - a*z)/norma(y - a*z)
        #генерирование матрицы отражений - U
        U = np.eye(n-i,n-i) - 2*np.transpose(w)*w
        U = np.block([[np.eye(n,n)[0:i,:]],[np.zeros((n-i,i)), U]])
        A = U*A
        b = U*b
    M = np.hstack((A, b)) # обратный ход метода Гаусса
    for i in range(n):
        for j in range(n):
            if abs(M[i,j]) < 10**(-10):
                M[i,j] = 0
        if M[i, i] != 1:
            M[i, :] *= 1 / M[i, i]
    for k in range(n - 1, 0, -1):
           for r in range(k - 1, -1, -1):
                if M[r, k]:
                    M[r, :] -= M[k, :] * M[r, k]
    return  (M[:,n])

In [2]:
#метод наискорейшего градиентного спуска
def steep(A,b):
    n = 0
    n = A.shape[0]
    x = np.zeros((n,1)) #начальное приближение
    # поиск вектора невязки
    r = A*x - b
    eps = 10**(-9)
    while norma(r)[0,0] > eps:
        n+=1
        a = A*r
        # вычисление длины шага
        lam = (1/2)*(np.transpose(r)*r)/(np.transpose(a)*r)
        x = x - lam[0,0]*r
        r = A*x - b
    return x

In [3]:
def out_table(A,b,k):
    n = A.shape[0]
    table = pd.DataFrame({"Гаусс":[],"Отражения":[],"Наискор.спуск":[],"Встроенная функция":[]})
    x1 = np.array(Gauss(A,b)).round(k)
    x2 = np.array(mir(A,b)).round(k)
    x3 = np.array(steep(A,b)).round(k)
    x4 = np.array(np.linalg.solve(A,b)).round(k)
    for i in range(n):
        line ={"Гаусс":x1[i,0],"Отражения":x2[i,0],"Наискор.спуск":x3[i,0],"Встроенная функция":x4[i,0]}
        table=table.append(line,ignore_index=True)
    return table

In [4]:
A

NameError: name 'A' is not defined

In [24]:
b1

matrix([[11],
        [13],
        [15]])

In [25]:
out_table(A,b1,7)

количество итераций при решении методом наискорейшего спуска - 38


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0    1.0        1.0            1.0                 1.0
1    1.0        1.0            1.0                 1.0
2    1.0        1.0            1.0                 1.0

In [26]:
D = np.matrix([[10, 2, 3, 4],[2, 40, 4,1,],[1, 1, 30, 1,],[2, 3, 4, 13]])
print(D)
b = np.matrix([[0],[9],[9],[9]])

[[10  2  3  4]
 [ 2 40  4  1]
 [ 1  1 30  1]
 [ 2  3  4 13]]


In [27]:
out_table(D,b,19)

количество итераций при решении методом наискорейшего спуска - 60


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0    0.0  -0.371765      -0.371765           -0.371765
1    0.0   0.199675       0.199675            0.199675
2    0.0   0.285214       0.285214            0.285214
3    0.0   0.615665       0.615665            0.615665

In [374]:
B1

matrix([[ 1.0007e+00, -1.0007e+00, -1.0007e+00, -1.0007e+00, -1.0007e+00],
        [ 7.0000e-04,  1.0007e+00, -1.0007e+00, -1.0007e+00, -1.0007e+00],
        [ 7.0000e-04,  7.0000e-04,  1.0007e+00, -1.0007e+00, -1.0007e+00],
        [ 7.0000e-04,  7.0000e-04,  7.0000e-04,  1.0007e+00, -1.0007e+00],
        [ 7.0000e-04,  7.0000e-04,  7.0000e-04,  7.0000e-04,  1.0007e+00]])

In [28]:
out_table(B1,b12,2)

количество итераций при решении методом наискорейшего спуска - 58


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0    0.0        0.0            0.0                 0.0
1    0.0       -0.0            0.0                 0.0
2    0.0        0.0            0.0                 0.0
3    0.0        0.0            0.0                 0.0
4   -1.0       -1.0           -1.0                -1.0

In [29]:
out_table(B2,b12,2)

количество итераций при решении методом наискорейшего спуска - 52


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0   -0.0        0.0            0.0                -0.0
1   -0.0        0.0           -0.0                -0.0
2   -0.0        0.0           -0.0                -0.0
3    0.0        0.0           -0.0                -0.0
4   -1.0       -1.0           -1.0                -1.0

In [30]:
out_table(B3,b34,2)

количество итераций при решении методом наискорейшего спуска - 175


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0    0.0       -0.0           -0.0                 0.0
1    0.0       -0.0           -0.0                 0.0
2    0.0       -0.0           -0.0                 0.0
3    0.0       -0.0           -0.0                 0.0
4    0.0       -0.0           -0.0                 0.0
5   -1.0       -1.0           -1.0                -1.0

In [36]:
out_table(B4,b34,2)

количество итераций при решении методом наискорейшего спуска - 64


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0   -0.0       -0.0            0.0                -0.0
1   -0.0       -0.0            0.0                -0.0
2   -0.0       -0.0            0.0                -0.0
3   -0.0        0.0            0.0                -0.0
4   -0.0        0.0            0.0                -0.0
5   -1.0       -1.0           -1.0                -1.0

In [32]:
out_table(B5,b56,2)

количество итераций при решении методом наискорейшего спуска - 1138


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0   -0.0        0.0           -0.0                -0.0
1   -0.0        0.0           -0.0                -0.0
2   -0.0        0.0           -0.0                -0.0
3   -0.0        0.0           -0.0                 0.0
4   -0.0        0.0           -0.0                -0.0
5   -0.0        0.0           -0.0                 0.0
6   -1.0       -1.0           -1.0                -1.0

In [34]:
out_table(B6,b56,2)

количество итераций при решении методом наискорейшего спуска - 101


Гаусс  Отражения  Наискор.спуск  Встроенная функция
0   -0.0       -0.0            0.0                 0.0
1   -0.0       -0.0            0.0                 0.0
2   -0.0       -0.0           -0.0                 0.0
3    0.0       -0.0            0.0                 0.0
4    0.0       -0.0            0.0                 0.0
5    0.0       -0.0           -0.0                 0.0
6   -1.0       -1.0           -1.0                -1.0

In [35]:
n = B4.shape[0]
B4_obr = Gauss(B4,np.eye(n))
np.array(B4*B4_obr).round()

array([[ 1.,  0., -0.,  0.,  0., -0.],
       [ 0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  1., -0., -0., -0.],
       [ 0.,  0.,  0.,  1., -0., -0.],
       [ 0.,  0.,  0.,  0.,  1., -0.],
       [ 0., -0., -0., -0.,  0.,  1.]])