In [1]:
import pandas as pd
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
import math as m

A = [[2*2, 1, 1],
    [1, 3.6*2, -1],
    [1, -1, 4.6*2]]
b = [[1],
     [-2],
     [3]]

In [2]:
# ищем дельта для останова
def delt(A):
    n = len(A)
    s = 0
    for i in range(n):
        for j in range(n):
            if i != j:
                s +=A[i][j]
    ans = 90
    for i in range(n):
        d = A[i][i] - s
        if d < ans: ans = d
    return d

In [3]:
# транспонирование матрицы
def t(A):
    n = len(A)
    m = len(A[0])
    B = []
    for i in range(m):
        C = []
        for j in range(n):
            C[len(C):] = [A[j][i]]
        B[len(B):] = [C]
    return B
        

In [4]:
# сумма матриц
def s(A,B):
    
    if len(A[0]) == len(B[0]) and len(A) == len(B)  :
        C = B
        n = len(A)
        for i in range(len(A)):
            for j in range(len(A[0])):
                C[i][j] = B[i][j] + A[i][j]
    else: return "oops"
    return C
        

In [5]:
# перемножение матриц
def d(A,B):
    ans = []
    for i in range(len(A)):
        for j in range(len(B[0])):
            an = []
            a = 0
            for k in range(len(B)):
                a += A[i][k] * B[k][j]
            an[len(an):] = [a]
        ans[len(ans):] = [an]
    return ans

In [6]:
def dn(a,A):
    for i in range(len(A)):
        for j in range(len(A[0])):
            A[i][j] *= a
    return A

In [7]:
# норма вектора 
def norma(b):
    s = 0
    for i in range(len(b)):
        for j in range(len(b[0])):
            s +=b[i][j]**2
    return s**(1/2)

In [8]:
def steep(A,b):
    k = 0
    n = len(A)
    # начальное приближение
    x0 = [[0]]*n
    x1 = [[1]]*n
    # поиск градиента
    df = s(d(A,x0),b)
    eps = 10**(-6)
    de = delt(A)
    while norma(df)/de > eps:
        k += 1
        # вычисление длины шага
        lam = d(t(df),df)[0][0]/d(t(df),d(A,df))[0][0]
        x1 = x0
        # переход к новой точке
        x0 = s(x0, dn(-lam,df))
        df = s(d(A,x0),b)
    print("количество итераций: ",k)
    return x0

In [9]:
steep(A,b)
# координаты найденной методом наискорейшего спуска точки минимума

количество итераций:  448


[[0.0], [0.0], [0.0]]

In [10]:
def coordinates(A,b):
    k = 0
    n = len(A)
    eps = 10**(-6)
    x0 = [[0]]*n
    x1 = [[1]]*n
    df = s(d(A,x0),b)
    de = delt(A)
    E = np.eye(n)
    while norma(df)/de > eps:
        for i in range(n):
            k += 1
            q = E[i]
            q = list(q[np.newaxis,:])
            qt = t(q)
            lam = -d(q,df)[0][0]/d(q,d(A,qt))[0][0]
            x1 = x0
            x0 = s(x0,dn(lam,qt))
            df = df = s(d(A,x0),b)
    print("количество итераций: ",k)
    return x0

In [11]:
coordinates(A,b)
# координаты найденной методом покоординатного спуска точки минимума

количество итераций:  0


[[0], [0], [0]]

In [12]:
A1 = np.matrix([[2*2, 1, 1],
    [1, 3.6*2, -1],
    [1, -1, 4.6*2]])
b1 = np.array([[1],
     [-2],
     [3]])

In [20]:
Gauss(A1,-b1)
# координаты точки минимума, найденные с помощью метода Гаусса

matrix([[-0.25164908],
        [ 0.27539578],
        [-0.26879947]])

In [21]:
v_steep = steep(A,b)
f_steep = (d(t(v_steep),d(A,v_steep)) + d(t(v_steep),t(b)) + 6)
print(f_steet)
# значение в найденной точке (наискорейший спуск)

количество итераций:  0


TypeError: can only concatenate list (not "int") to list

In [22]:
v_coordinates = coordinates(A,b)
f_coordinates = (v_coordinates[:,0]*A*v_coordinates + sum(v_coordinates*b) + 6)[0,0]
print(f_coordinates)
# значение в найденной точке (покоординатный спуск)

количество итераций:  0


TypeError: list indices must be integers or slices, not tuple

In [23]:
v_Gauss = np.array(Gauss(A1,-b1))
f_Gauss = (v_Gauss[:,0]*A1*v_Gauss + sum(v_Gauss*b1) + 6)[0,0]
print(f_Gauss)
# значение в найденной точке (Гаусс)

6.0


In [17]:
print("абсолютная погрешность метода наискорейшего спуска:",abs(f_Gauss -f_steep) )
print("абсолютная погрешность метода покоординатного спуска:",abs(f_Gauss - f_coordinates) )

NameError: name 'f_Gauss' is not defined

In [18]:
def Gauss(A,b):
        M = np.hstack((A, b)) # "склейка" матрицы коэффициентов при переменных и вектора свободных членов
        n = M.shape[0] 
        for k in range(n): 
            # убираем нули с главной диагонали, если они есть
            k0 = no0(M, k)
            if k0 != k:
                M[k0], M[k] = M[k].copy(), M[k0]   
            if M[k, k] != 1:
                M[k, :] *= 1 / M[k, k]
            # приямой ход метода Гаусса
            for r in range(k + 1, n):
                M[r, :] -= M[k, :] * M[r, k]
        #обратный ход метода Гаусса
        for k in range(n - 1, 0, -1):
            for r in range(k - 1, -1, -1):
                if M[r, k]:
                    M[r, :] -= M[k, :] * M[r, k]
        if b.shape[1] > 1:
            return np.hsplit(M,2)[1]
        return  (M[:,n])

In [19]:
# проверяем, есть ли на главной диагонали нули
def no0(M, k):
    n =  M.shape[0]
    while k < n and not M[k, k]:
        k += 1
    return k

SyntaxError: unexpected EOF while parsing (<ipython-input-15-8dae99bda89b>, line 3)

In [16]:
-b

array([[-1],
       [ 2],
       [-3]])

In [17]:
A

matrix([[ 4. ,  1. ,  1. ],
        [ 1. ,  7.2, -1. ],
        [ 1. , -1. ,  9.2]])