In [10]:
import pandas as pd
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
import math as m

x,y,z = sp.symbols('x, y, z')
A = np.matrix([[4, 1, 1],[1, 3.6*2, -1],[1, -1, 4.6*2]])
b = (np.matrix([1, -2, 3])).T
print(A)
print(b)

[[ 4.   1.   1. ]
 [ 1.   7.2 -1. ]
 [ 1.  -1.   9.2]]
[[ 1]
 [-2]
 [ 3]]


In [18]:
def norma1(A):
    n = A.shape[0]
    s = 0
    s1 = 0
    for i in range(n):
        if s > s1:
            s1 = s
        s = 0
        for j in range(n):
            s += abs(A[i,j])
    if s > s1:
            s1 = s
    return s1

2x^2+3.6y^2+4.6z^2+xy-yz+xz+x-2y+3z+6

In [11]:
Absf = 5.195580474934037
Absf

5.195580474934037

In [19]:
def steep(A,b):
    n = 0
    n = A.shape[0]
    # начальное приближение
    x0 = np.zeros((n,1))
    x1 = np.ones((n,1))
    # поиск градиента
    df = A*x0 + b
    eps = 10**(-6)
    while norma1(x1 - x0) > eps:
        # вычисление длины шага
        lam = (np.transpose(df)*df)/(np.transpose(df)*A*df)
        x1 = x0
        # переход к новой точке
        x0 = x0 - lam[0,0]*df
        df = A*x0 + b
    return x0

In [20]:
steep(A,b)
# координаты найденной точки минимума

IndexError: index 1 is out of bounds for axis 1 with size 1

In [17]:
vec = steep(A,b)
f1 = (vec.T*A*vec + vec.T*b + 6)[0,0]
print(f1)
# значение в найденной точке

5.999999940763598


In [6]:
f1 - Absf


0.8044194658295618

In [7]:
def coordinates(A,b):
    eps = 10**(-6)
    x0 = np.zeros((3,1))
    x1 = np.ones((3,1))
    df = A*x0 + b
    nor =np.linalg.norm(x1 - x0)
    E = np.eye(3)
    while nor > eps:
        for i in range(3):
            q = E[i]
            q = q[np.newaxis,:]
            qt = q.T
            lam = -(q*df)/(q*A*qt)
            x1 = x0
            x0 = x0 + lam[0,0]*qt
            df = A.dot(x0) + b
        nor =np.linalg.norm(x1 - x0)
    return x0

In [8]:
print(coordinates(A,b)[0,0])
print(coordinates(A,b)[1,0])
print(coordinates(A,b)[2,0])

-0.2516492276807371
0.2753958257132
-0.26879945071805034


In [9]:
vec1 = coordinates(A,b)
f2 = (vec1.T*A*vec1 + vec1.T*b + 6)[0,0]
print(f2)

6.000000181129451


In [16]:
f2 - Absf

0.8044197061954144

In [17]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])